$(document).ready(function(){
                  var newCopyPasta = new Array(4);

                  var job = [ "Dental",
                        "Med",
                        "Nursing",
                        "Law",
                        "Pharmacy",
                        "Education",
                        "Graduate School",

                  ];

                  var hobbies = [ "Painter.",
                        "Photographer.",
                        "Musician.",
                        "Author.",
                        "3D Printing.",
                        "Animal fancying.",
                        "Amateur radio.",
                        "Audiophilia.",
                        "Baton twirling.",
                        "Bboying.",
                        "Blogging.",
                        "Chainmail making.",
                        "Coloring.",
                        "Computer programming.",
                        "Conlanging.",
                        "Cooking.",
                        "Cosplaying.",
                        "Creative writing.",
                        "Crocheting.",
                        "Dancing.",
                        "Digital arts.",
                        "Drama.",
                        "Drawing.",
                        "Drinking Coffee.",
                        "Eating.",
                        "Embroidery.",
                        "Fantasy Sports.",
                        "Fishkeeping.",
                        "Foreign languages.",
                        "Gaming.",
                        "Genealogy.",
                        "Genetic genealogy.",
                        "Herpetoculture.",
                        "Home Movies.",
                        "Homebrewing.",
                        "Jewelry making.",
                        "Juggling.",
                        "Knapping.",
                        "Knitting.",
                        "K-pop.",
                        "Lacemaking.",
                        "Lapidary.",
                        "Leather crafting.",
                        "Lego Builder.",
                        "Locksport.",
                        "Magic.",
                        "Modeling.",
                        "Model Building.",
                        "Model Railroading.",
                        "Netflix.",
                        "Origami.",
                        "Painting.",
                        "Planning to take over the world.",
                        "Ping Pong.",
                        "Playing Music.",
                        "Pottery.",
                        "Quilting.",
                        "RC cars.",
                        "Reading.",
                        "Scrapbooking.",
                        "Sculpting.",
                        "Sewing.",
                        "Singing.",
                        "Soapmaking.",
                        "Speedsolving.",
                        "Stand-Up Comedy.",
                        "Taxidermy.",
                        "Watching Movies.",
                        "Web surfing.",
                        "Wood carving.",
                        "Woodworking.",
                        "Worldbuilding.",
                        "Writing.",
                        "Yoga.",
                        "Yo-yoing.",
                        "Archery.",
                        "Air sports.",
                        "Backpacking.",
                        "BASE jumping.",
                        "Baseball.",
                        "Basketball.",
                        "Beekeeping.",
                        "Bird watching.",
                        "Board sports.",
                        "Driving.",
                        "Fishing.",
                        "Foraging.",
                        "Gardening.",
                        "Geocaching.",
                        "Ghost Hunting.",
                        "Graffiti.",
                        "Handball.",
                        "Hiking.",
                        "Hooping.",
                        "Hunting.",
                        "Inline Skating.",
                        "Jogging.",
                        "Kayaking.",
                        "Kiteboarding.",
                        "Kiteflying.",
                        "LARPing.",
                        "Machining.",
                        "Metal detecting.",
                        "Motor sports.",
                        "Mountain biking.",
                        "Mushroom Hunting or Mycology.",
                        "Nordic skating.",
                        "Paint Ball.",
                        "Parkour.",
                        "Photography.",
                        "Rock climbing.",
                        "Roller skating.",
                        "Rugby.",
                        "Running.",
                        "Sailing.",
                        "Sand castle building.",
                        "Scuba Diving.",
                        "Rowing.",
                        "Shooting.",
                        "Skating.",
                        "Skateboarding.",
                        "Skiing.",
                        "Skydiving.",
                        "Slacklining.",
                        "Surfing.",
                        "Snowboarding.",
                        "Swimming.",
                        "Taekwondo.",
                        "Tai Chi.",
                        "Urban explorer.",
                        "Vehicle restorer.",
                        "Water sports.",
                        "Net Ball.",
                        "Antiquing.",
                        "Art collecting.",
                        "Book collecting.",
                        "Card collecting.",
                        "Coin collecting.",
                        "Postcards.",
                        "Element collecting.",
                        "Modelling.",
                        "Record collecting.",
                        "Stamp collecting.",
                        "Stone collecting.",
                        "Vintage Books.",
                        "Vintage cars.",
                        "Vintage clothing.",
                        "Antiquities.",
                        "Car Stereos.",
                        "Flower pressing.",
                        "Fossil hunting.",
                        "Insect collecting.",
                        "Leaf pressing.",
                        "Metal detecting.",
                        "Mineral collecting.",
                        "Rock stacking.",
                        "Seaglass collecting.",
                        "Seashell collecting.",
                        "Animal showing.",
                        "Badminton.",
                        "Billiards.",
                        "Bowling.",
                        "Boxing.",
                        "Bridge.",
                        "Cheerleading.",
                        "Chess.",
                        "Color Guard.",
                        "Cubing.",
                        "Curling.",
                        "Cricket.",
                        "Dancing.",
                        "Darts.",
                        "Fencing.",
                        "Gaming.",
                        "Go.",
                        "Gymnastics.",
                        "Marbles.",
                        "Martial arts.",
                        "Poker.",
                        "Pole dancing.",
                        "Table football.",
                        "Volleyball.",
                        "Weightlifting.",
                        "Airsoft.",
                        "Archery.",
                        "Soccer.",
                        "Australian Football League.",
                        "Auto racing.",
                        "Baseball.",
                        "Basketball.",
                        "Climbing.",
                        "Cricket.",
                        "Cycling.",
                        "Disc golf.",
                        "Dog sport.",
                        "Equestrianism.",
                        "Exhibition Drill.",
                        "Field Hockey.",
                        "Figure skating.",
                        "Fishing.",
                        "Footbag.",
                        "Football.",
                        "Golfing.",
                        "Handball.",
                        "Ice hockey.",
                        "Jugger.",
                        "Judo.",
                        "Jukskei.",
                        "Kart racing.",
                        "Model aircraft.",
                        "Paintball.",
                        "Pigeon racing.",
                        "Programming.",
                        "Racquetball.",
                        "Roller Derby.",
                        "Rugby.",
                        "Running.",
                        "Shooting sport.",
                        "Skateboarding.",
                        "Slot car racing.",
                        "Speed skating.",
                        "Squash.",
                        "Surfing.",
                        "Swimming.",
                        "Masturbating.",
                        "Table tennis.",
                        "Target shooting.",
                        "Tennis.",
                        "Touch football.",
                        "Tour skating.",
                        "Triathlon.",
                        "Volleyball.",
                        "Indoors.",
                        "Audiophilia.",
                        "Microscopy.",
                        "Reading.",
                        "Shortwave listening.",
                        "Videophile.",
                        "Outdoors.",
                        "Aircraft spotting.",
                        "Amateur astronomy.",
                        "Amateur geology.",
                        "Astrology.",
                        "Auto Racing.",
                        "Birdwatching.",
                        "Bus spotting.",
                        "College football.",
                        "Geocaching.",
                        "Gongoozling.",
                        "Herping.",
                        "Meteorology.",
                        "People watching.",
                        "Trainspotting.",
                        "Travel.",
                        "Free Spirit.",
                        "Instagram.",
                        "Craft Beer.",
                        "Bars.",
                        "Liberal.",
                        "Hippie.",
                        "College Student.",
                        "Musicals.",
                        "5ks.",

                  ];

                  var quotes = [ "\"If you can't handle me at my worst, you don't deserve me at my best\" -Marilyn Monroe.",
                        "Not looking for a relationship.",
                        "Live. Laugh. Love.",
                        "Not a woman that needs a man.",
                        "\"Well behaved women rarely make history\" -Eleanor Roosevelt.",
                        "R-E-S-P-E-C-T.",
                        "Not here for hookups.",
                        "Do what makes you happy.",
                        "I do what I want.",
                        "Not really 22, actually 18.",
                        "Friends convinced me to get this app.",
                        "Down for new experiences.",
                        "I believe you should never make someone a priority who sees you as an option.",
                        "Our kids would look beautiful.",
                        "Love and be loved.",
                        "Just a small town girl chasing big dreams.",
                        "Haters gonna hate.",
                        "Life's short.",
                        "When you stop growing and changing you start dying.",
                        "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
                        "I have many leather bound books and my apartment smells of rich mahogany.",
                        "Brown shoes and rubix cubes.",
                        "Down to lie about how we met.",
                        "Leviticus 26:29.",
                        "I don't do love.",
                        "\"So flee youthful passions and pursue righteousness, faith, love, and peace, along with those who call on the Lord from a pure heart\" Timothy 2:22",
                        "\"Flee from sexual immorality. Every other sin a person commits is outside the body, but the sexually immoral person sins against his own body\" -Corinthians 6:18.",
                        "12 inches. I'll leave it up to the imagination.",
                        "I'm a nice guy.",
                        "I'm a nice girl.",

                  ];
                  
                  $('#button').click(function(e){
                                     e.preventDefault();
                                     var i, j, dupC1="", dupC2="";
                                     for(i = 0; i < newCopyPasta.length; i++){
                                          j = Math.floor(Math.random()*(hobbies.length));
                                          if(dupC2 != hobbies[j] && dupC1 != hobbies[j] && hobbies[j] != "undefined" && hobbies[j] != null){
                                            if(i != 3){
                                                newCopyPasta[i] = hobbies[j] + " ";
                                            } else { newCopyPasta[i] = hobbies[j]; }
                                            dupC2 = dupC1;
                                            dupC1 = newCopyPasta[i];
                                          } else { i--; }
                                     }
                                     
                                     $('div#job').html("<p>Pre-" + job[(Math.floor(Math.random()*job.length))] + ".</p>");
                                     $('div#hobbies').html("<p>" + newCopyPasta[0]  + newCopyPasta[1]  + newCopyPasta[2] + " Oh, and " + newCopyPasta[3] + "</p>");
                                     $('div#quote').html("<p>" + quotes[(Math.floor(Math.random()*quotes.length))] + "</p>");
                                     });
                  });






