$(document).ready(function(){
                  var newGenre = new Array(3);
                  var genres = [ "Afrobeat",
                  "Apala",
                  "Benga",
                  "Bongo Flava",
                  "Bikutsi",
                  "Cape Jazz",
                  "Chimurenga",
                  "Fuji music",
                  "Genge",
                  "Highlife",
                  "Hiplife",
                  "Isicathamiya",
                  "Jit",
                  "Jùjú",
                  "Kapuka ",
                  "Kizomba",
                  "Kuduro",
                  "Kwaito",
                  "Kwela",
                  "Makossa",
                  "Maloya",
                  "Marrabenta",
                  "Mbalax",
                  "Museve ",
                  "Mbaqanga",
                  "Mbube",
                  "Morna",
                  "Palm-wine music",
                  "Raï",
                  "Reggae",
                  "Sakara",
                  "Sega",
                  "Semba",
                  "Soukous ",
                  "Taarab",
                  "Zouglou ",
                  "Avante Garde",
                  "Experimental music",
                  "Noise",
                  "Lo-fi",
                  "Musique concrète",
                  "Blues",
                  "African blues",
                  "Blues rock",
                  "Blues shouter",
                  "British blues",
                  "Canadian blues",
                  "Chicago blues",
                  "Classic female blues",
                  "Contemporary R&B",
                  "Country blues",
                  "Delta blues",
                  "Detroit blues",
                  "Electric blues",
                  "Gospel blues",
                  "Hill country blues",
                  "Hokum",
                  "Jazz blues",
                  "Jump blues",
                  "Kansas City blues",
                  "Louisiana blues",
                  "Memphis blues",
                  "Piano blues",
                  "Piedmont blues",
                  "Punk blues",
                  "Rhythm and blues",
                  "Soul blues",
                  "St. Louis blues",
                  "Swamp blues",
                  "Texas blues",
                  "West Coast blues",
                  "Axé",
                  "Bossa Nova",
                  "Brazilian rock",
                  "Brega",
                  "Choro",
                  "Forró",
                  "Frevo",
                  "Funk Carioca",
                  "Lambada",
                  "Maracatu",
                  "Música Popular Brasileira",
                  "Música sertaneja",
                  "Pagode",
                  "Rap",
                  "Samba",
                  "Samba rock",
                  "Tecnobrega",
                  "Tropicalia",
                  " zouk-lambada",
                  "Comedy music",
                  "Comedy rock",
                  "Parody music",
                  "Alternative country",
                  "Cowpunk",
                  "Blues country",
                  "Hellbilly music",
                  "Hokum",
                  "Outlaw country",
                  "Progressive country",
                  "Psychobilly",
                  "Punkabilly",
                  "Zydeco",
                  "Rap country",
                  "Red Dirt",
                  "Rockabilly",
                  "Rock country",
                  "Soul country",
                  "Techno country",
                  "Texas country",
                  "Americana",
                  "Australian country music",
                  "Bakersfield sound",
                  "Bluegrass",
                  "Bluegrass",
                  "Appalachian bluegrass",
                  "Progressive bluegrass",
                  "Reactionary bluegrass",
                  "Cajun",
                  "Cajun fiddle",
                  "Christian country music",
                  "Classic country",
                  "Close harmony",
                  "Cowboy/Western",
                  "Dansband",
                  "Franco-country",
                  "Gulf and western",
                  "Honky Tonk",
                  "Instrumental country",
                  "Lubbock Sound",
                  "Nashville Sound",
                  "Neotraditional Country",
                  "New country",
                  "Pop country",
                  "Cosmopolitan country",
                  "Sertanejo",
                  "Traditional Country music",
                  "Truck-driving country",
                  "Western swing",
                  "Anison",
                  "Cantopop",
                  "C-pop",
                  "Enka",
                  "Hong Kong English pop",
                  "J-pop",
                  "Kayōkyoku",
                  "K-pop",
                  "Mandopop",
                  "Onkyokei",
                  "Taiwanese pop",
                  "Adult Contemporary",
                  "Background music",
                  "Beautiful music",
                  "Elevator music",
                  "Furniture music",
                  "Lounge music",
                  "Middle of the road",
                  "New Age music",
                  "Electronic music",
                  "Electronica",
                  "Ambient",
                  "Ambient dub",
                  "Ambient house",
                  "Ambient techno",
                  "Dark ambient",
                  "Drone music",
                  "Illbient",
                  "Isolationism",
                  "Lowercase",
                  "Asian Underground",
                  "Breakbeat",
                  "Breakbeat",
                  "Acid breaks",
                  "Baltimore Club",
                  "Big beat",
                  "Breakbeat hardcore",
                  "Hardcore breaks",
                  "Broken beat",
                  "Florida breaks",
                  "Nu skool breaks",
                  "4-beat",
                  "Chiptune",
                  "Bitpop",
                  "Game Boy music",
                  "Nintendocore",
                  "Video game music",
                  "Yorkshire Bleeps and Bass",
                  "Disco",
                  "Cosmic disco",
                  "Disco polo",
                  "Europop",
                  "Euro disco",
                  "Space disco",
                  "Italo disco",
                  "Nu-disco",
                  "Downtempo",
                  "Acid jazz",
                  "Balearic Beat",
                  "Chill out",
                  "Dub music",
                  "Dubtronica",
                  "Ethnic electronica",
                  "Moombahton",
                  "New age music",
                  "Nu jazz",
                  "Trip hop",
                  "Drum and bass",
                  "Darkcore",
                  "Darkstep",
                  "Drumfunk",
                  "Drumstep",
                  "Hardstep",
                  "Intelligent drum and bass",
                  "Jump-Up",
                  "Liquid funk",
                  "Neurofunk",
                  "Oldschool jungle",
                  "Darkside jungle",
                  "Ragga-jungle",
                  "Raggacore",
                  "Sambass",
                  "Electro",
                  "Crunk",
                  "Electro backbeat",
                  "Electro-grime",
                  "Electropop",
                  "Electroacoustic",
                  "Acousmatic music",
                  "Computer music",
                  "Electroacoustic improvisation",
                  "Field recording",
                  "Live electronics",
                  "Live coder",
                  "Musique concrète",
                  "Soundscape composition",
                  "Tape music",
                  "Electronica",
                  "Berlin school",
                  "Chillwave",
                  "Electronic art",
                  "Electronic dance",
                  "Folktronica",
                  "Freestyle music",
                  "Intelligent dance music",
                  "Glitch",
                  "Laptronica",
                  "Rave breaks",
                  "Skweee",
                  "Sound art",
                  "Synthcore",
                  "Electronic rock",
                  "Alternative dance",
                  "Baggy",
                  "Madchester",
                  "Dance-punk",
                  "Dance-rock",
                  "Dark Wave",
                  "Electroclash",
                  "Electropunk",
                  "Ethereal Wave",
                  "Indietronica",
                  "New rave",
                  "Space rock",
                  "Synthpop",
                  "Synthpunk",
                  "Trip rock",
                  "Eurodance",
                  "Bubblegum dance",
                  "Eurotrance",
                  "J-pop",
                  "Italo dance",
                  "Turbofolk",
                  "Hardcore",
                  "Hard dance",
                  "Bouncy house",
                  "Bouncy techno",
                  "Breakcore",
                  "Darkcore",
                  "Digital hardcore",
                  "Doomcore",
                  "Gabber",
                  "Happy hardcore",
                  "Hardstyle",
                  "Jumpstyle",
                  "Makina",
                  "Speedcore",
                  "Terrorcore",
                  "UK hardcore",
                  "Hi-NRG",
                  "Eurobeat",
                  "Hard NRG",
                  "New Beat",
                  "House",
                  "Acid house",
                  "Chicago house",
                  "Deep house",
                  "Diva house",
                  "Dutch house",
                  "Electro house",
                  "French house",
                  "Freestyle house",
                  "Funky house",
                  "Ghetto house",
                  "Hardbag",
                  "Hip house",
                  "Italo house",
                  "Latin house",
                  "Microhouse",
                  "Progressive House",
                  "Rave music",
                  "Swing house",
                  "Tech house",
                  "Tribal house",
                  "UK Hard house",
                  "US garage",
                  "Vocal house",
                  "Industrial",
                  "Aggrotech",
                  "Coldwave",
                  "Cybergrind",
                  "Dark electro",
                  "Death industrial",
                  "Electronic body music",
                  "Futurepop",
                  "Electro-Industrial",
                  "Industrial metal",
                  "Neue Deutsche Härte",
                  "Industrial rock",
                  "Noise",
                  "Japanoise",
                  "Power noise",
                  "Power electronics",
                  "Witch House",
                  "Post-disco",
                  "Boogie",
                  "Dance-pop",
                  "Progressive",
                  "Progressive Breaks",
                  "Progressive Drum & Bass",
                  "Progressive House/Trance",
                  "Disco house",
                  "Dream house",
                  "Space house",
                  "Progressive techno",
                  "Techno",
                  "Acid techno",
                  "Detroit techno",
                  "Free tekno",
                  "Ghettotech",
                  "Minimal",
                  "Nortec",
                  "Rotterdam techno",
                  "Schranz",
                  "Symphonic techno",
                  "Tecno brega",
                  "Techno-DNB",
                  "Techstep",
                  "Toytown Techno",
                  "Trance",
                  "Acid trance",
                  "Classic trance",
                  "Dream trance",
                  "Euro-trance",
                  "Goa trance ",
                  "Psychedelic trance",
                  "Dark psytrance",
                  "Full on",
                  "Psyprog",
                  "Psybient",
                  "Psybreaks",
                  "Suomisaundi",
                  "Hard trance",
                  "Tech trance",
                  "Uplifting trance",
                  "Uplifting Trance",
                  "Vocal trance",
                  "UK garage",
                  "2-step garage",
                  "Speed garage",
                  "Bassline",
                  "Breakstep",
                  "Dubstep",
                  "Funky",
                  "Grime",
                  "Folk",
                  "Contemporary folk",
                  "Indie folk",
                  "Neofolk",
                  "Progressive folk",
                  "Anti-folk",
                  "Freak folk",
                  "Filk music",
                  "American folk revival",
                  "British folk revival",
                  "Industrial folk",
                  "Techno-folk",
                  "Psychedelic folk",
                  "Sung poetry",
                  "Hip Hop",
                  "Old school hip hop",
                  "New school hip hop",
                  "Golden age hip hop",
                  "Alternative hip hop",
                  "Avant-garde hip hop",
                  "Chopped and screwed",
                  "Christian hip hop",
                  "Conscious hip hop",
                  "Country-rap",
                  "Crunk",
                  "Crunkcore",
                  "Electro music",
                  "Freestyle music",
                  "Freestyle rap",
                  "G-Funk",
                  "Gangsta rap",
                  "Ghetto house",
                  "Ghettotech",
                  "Grime",
                  "Hardcore hip hop",
                  "Hip hop soul",
                  "Hip house",
                  "Hip pop",
                  "Horrorcore",
                  "Hyphy",
                  "Industrial hip hop",
                  "Instrumental hip hop",
                  "Jazz rap",
                  "Lyrical hip hop",
                  "Mafioso rap",
                  "Nerdcore hip hop",
                  "New jack swing",
                  "Political hip hop",
                  "Ragga",
                  "Reggaeton",
                  "Rap opera",
                  "Rap rock",
                  "Rapcore",
                  "Rap metal",
                  "Snap music",
                  "Turntablism",
                  "Underground hip hop",
                  "East Coast hip hop",
                  "Baltimore club",
                  "Brick City club",
                  "Hardcore hip hop",
                  "Mafioso rap",
                  "New Jersey hip hop",
                  "Midwest hip hop",
                  "Chicago hip hop",
                  "Ghetto house",
                  "Detroit hip hop",
                  "Ghettotech",
                  "St. Louis hip hop",
                  "Twin Cities hip hop",
                  "Horrorcore",
                  "Southern hip hop",
                  "Atlanta hip hop",
                  "Snap music",
                  "Bounce music",
                  "Crunk",
                  "Houston hip hop",
                  "Chopped and screwed",
                  "Miami bass",
                  "West Coast hip hop",
                  "Chicano rap",
                  "Gangsta rap",
                  "G-funk",
                  "Hyphy",
                  "Jerkin'",
                  "Bongo Flava",
                  "Cumbia rap",
                  "Hiplife",
                  "Kwaito",
                  "Low Bap",
                  "Merenrap",
                  "Motswako",
                  "Spanish Reggae",
                  "Reggaeton",
                  "Songo-salsa",
                  "Trip hop ",
                  "Urban Pasifika",
                  "Jazz",
                  "Acid jazz",
                  "Asian American jazz",
                  "Avant-garde jazz",
                  "Bebop",
                  "Boogie-woogie",
                  "Bossa nova",
                  "British dance band",
                  "Cape jazz",
                  "Chamber jazz",
                  "Continental Jazz",
                  "Cool jazz",
                  "Crossover jazz",
                  "Cubop",
                  "Dixieland",
                  "Ethno jazz",
                  "European free jazz",
                  "Free funk",
                  "Free improvisation",
                  "Free jazz",
                  "Gypsy jazz",
                  "Hard bop",
                  "Jazz blues",
                  "Jazz-funk",
                  "Jazz fusion",
                  "Jazz rap",
                  "Jazz rock",
                  "Kansas City blues",
                  "Kansas City jazz",
                  "Latin jazz",
                  "Livetronica",
                  "M-Base",
                  "Mainstream jazz",
                  "Modal jazz",
                  "Neo-bop jazz",
                  "Neo-swing",
                  "Novelty ragtime",
                  "Nu jazz",
                  "Orchestral jazz",
                  "Post-bop",
                  "Punk jazz",
                  "Ragtime",
                  "Shibuya-kei",
                  "Ska jazz",
                  "Smooth jazz",
                  "Soul jazz",
                  "Stride jazz",
                  "Straight-ahead jazz",
                  "Swing",
                  "Third stream",
                  "Trad jazz",
                  "Vocal jazz",
                  "West Coast Gypsy jazz",
                  "West Coast jazz",
                  "Zeuhl",
                  "Latin American",
                  "Axé",
                  "Bachata",
                  "Baithak Gana",
                  "Bossa Nova",
                  "Calypso",
                  "Chutney",
                  "Chutney soca",
                  "Cumbia",
                  "Funk Carioca",
                  "Huayño",
                  "Kompa",
                  "Mambo",
                  "Mariachi",
                  "Merengue",
                  "Música Popular Brasileira",
                  "Ranchera",
                  "Reggaeton",
                  "Salsa",
                  "Samba",
                  "Soca",
                  "Son music",
                  "Tejano",
                  "Tropicalismo",
                  "Zouk",
                  "Pop",
                  "Arab pop",
                  "Baroque pop",
                  "Bubblegum pop",
                  "Classical crossover",
                  "Country pop",
                  "Dance-pop",
                  "Disco polo",
                  "Electropop",
                  "Europop",
                  "Austropop",
                  "Balkan pop",
                  "Eurobeat",
                  "French pop",
                  "Italo dance",
                  "Italo disco",
                  "Laïkó",
                  "Latin pop",
                  "Nederpop",
                  "Russian pop",
                  "Schlager",
                  "Iranian pop",
                  "Jangle pop",
                  "Levenslied",
                  "Swamp pop",
                  "Louisiana swamp pop",
                  "Mexican pop",
                  "Motorpop",
                  "New romantic",
                  "Popera",
                  "Pop rap",
                  "Psychedelic pop",
                  "Soft rock",
                  "Sophisti-pop",
                  "Space age pop",
                  "Sunshine pop",
                  "Surf pop",
                  "Synthpop",
                  "Teen pop",
                  "Traditional pop music",
                  "Turkish pop",
                  "Vispop",
                  "Wonky Pop",
                  "Contemporary R&B",
                  "Doo wop",
                  "Funk",
                  "Deep Funk",
                  "Disco",
                  "Post-disco",
                  "Boogie",
                  "Go-go",
                  "P-Funk",
                  "New jack swing",
                  "Soul",
                  "Blue-eyed soul",
                  "Hip hop soul",
                  "Northern soul",
                  "Neo soul",
                  "Rock",
                  "Alternative rock",
                  "Britpop",
                  "Post-Britpop",
                  "Dream pop",
                  "Grunge",
                  "Post-grunge",
                  "Indie pop",
                  "Dunedin Sound",
                  "Twee Pop",
                  "Indie rock",
                  "Industrial rock",
                  "Noise pop",
                  "Nu metal",
                  "Post-punk revival",
                  "Post-rock",
                  "Post-metal",
                  "Sadcore",
                  "Shoegazer",
                  "Slowcore",
                  "Art rock",
                  "Beat music",
                  "Chinese rock",
                  "Dark cabaret",
                  "Experimental rock",
                  "Electronic rock",
                  "Folk rock",
                  "Garage rock",
                  "Glam rock",
                  "Hard rock",
                  "Heavy metal",
                  "Black metal",
                  "Viking Metal",
                  "Christian metal",
                  "Death metal",
                  "Melodic Death Metal",
                  "Technical Death Metal",
                  "Goregrind",
                  "Doom metal",
                  "Drone metal",
                  "Folk metal",
                  "Celtic metal",
                  "Medieval metal",
                  "Funk metal",
                  "Glam metal",
                  "Gothic metal",
                  "Industrial metal",
                  "Metalcore",
                  "Deathcore",
                  "Mathcore",
                  "Djent",
                  "Power metal",
                  "Progressive metal",
                  "Sludge metal",
                  "Speed metal",
                  "Stoner rock",
                  "Symphonic metal",
                  "Thrash metal",
                  "Crossover Thrash Metal",
                  "Groove metal",
                  "Jazz-Rock",
                  "Math rock",
                  "New Wave",
                  "World Fusion",
                  "Paisley Underground",
                  "Desert rock",
                  "Pop rock",
                  "Power pop",
                  "Progressive rock",
                  "Canterbury scene",
                  "Krautrock",
                  "New Prog",
                  "Rock in Opposition",
                  "Space rock",
                  "Psychedelic rock",
                  "Acid rock",
                  "Freakbeat",
                  "Neo-psychedelia",
                  "Raga rock",
                  "Punk rock",
                  "Anarcho punk",
                  "Crust punk",
                  "D-beat",
                  "Art punk",
                  "Deathrock",
                  "Digital Hardcore",
                  "Folk punk",
                  "Celtic punk",
                  "Cowpunk",
                  "Gypsy punk",
                  "Garage punk",
                  "Grindcore",
                  "Crustgrind",
                  "Noisegrind",
                  "Hardcore punk",
                  "Post-hardcore",
                  "Emo",
                  "Screamo",
                  "Thrashcore",
                  "Crossover Thrash Metal",
                  "Powerviolence",
                  "Street punk",
                  "Horror punk",
                  "Pop punk",
                  "Psychobilly",
                  "Riot grrrl",
                  "Ska punk",
                  "Skacore",
                  "Skate Punk",
                  "Post-punk",
                  "Gothic rock",
                  "No Wave",
                  "Noise rock",
                  "Rap rock",
                  "Rap metal",
                  "Rapcore",
                  "Rock and roll",
                  "Southern rock",
                  "Sufi rock",
                  "Surf rock",
                  "Visual kei",
                  "Nagoya kei",
                  "Ska",
                  "2 tone",
                  "Dancehall",
                  "Dub",
                  "Lovers rock",
                  "Ragga",
                  "Reggae",
                  "Polish reggae",
                  "Reggaefusion",
                  "Rocksteady",
                  "Asian",
                  "Baila",
                  "Bhangra",
                  "Dangdut",
                  "Filmi",
                  "Indian pop",
                  "Luk Thung",
                  "Luk Krung",
                  "Manila Sound",
                  "Morlam",
                  "Pinoy pop",
                  "Pop sunda",
                  "Thai pop",
                  "Worldbeat",
                  "Psychadelic music",
                  "Polka"
                  ];
                  
                  $('#button').click(function(e){
                                     e.preventDefault();
                                     var i, j, dupC1="", dupC2="";
                                     for(i = 0; i < 3; i++){
                                        j = Math.floor(Math.random()*769)
                                     if(dupC2 != genres[j] && dupC1 != genres[j] && genres[j] != "undefined" && genres[j] != null){
                                            if(i != 2){
                                                newGenre[i] = genres[j] + " ";
                                            } else { newGenre[i] = genres[j]; }
                                            dupC2 = dupC1;
                                            dupC1 = newGenre[i];
                                        } else { i--; }
                                     }
                                     
                                     $('div#genre').html("<a href='http://en.wikipedia.org/wiki/" + newGenre[0] + "' target='_blank'>" + newGenre[0].replace("music","") + "</a>" +
                                                         "<a href='http://en.wikipedia.org/wiki/" + newGenre[1] + "' target='_blank'>" + newGenre[1].replace("music","") + "</a>" +
                                                         "<a href='http://en.wikipedia.org/wiki/" + newGenre[2] + "' target='_blank'>" + newGenre[2].replace("music","") + "</a>");
                                     
                                     });
                  $('#shareonfb').click(function(e){
                                        e.preventDefault();
                                        var message_str= "Just started listening to some new " + newGenre[0] + " " + newGenre[1] + " " + newGenre[2] + ", you've probably never heard of it";
                                        FB.init({
                                                appId: '487803194612278',
                                                status: true,
                                                cookie: false,
                                                xfbml: true
                                                });
                                        FB.ui(
                                              {
                                              method: 'feed',
                                              name: 'Hipster Music',
                                              redirect_uri: 'http://www.williamflaherty.com/hipster/thanks.html',
                                              link: 'http://www.williamflaherty.com/hipster/',
                                              caption: 'Hipster Music',
                                              description: message_str
                                              },
                                              function(response) {
                                              if (response && response.post_id) {
                                              alert('Post was published.');
                                              } else {
                                              alert('Post was not published.');
                                              }
                                              }
                                              );
                 
                  
                  });

                  });